# Generated by Django 3.2.16 on 2023-06-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breach_app', '0003_userprofile_is_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='search_count',
            field=models.IntegerField(default=3),
        ),
    ]
