# Generated by Django 3.2.16 on 2023-06-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breach_app', '0004_alter_userprofile_search_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='search_count',
            field=models.IntegerField(default=0),
        ),
    ]
